// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96GWayylvZujOSDsLjaZ8EyCrunPaNU4',
    appId: '1:173268327760:web:d0ba2f53149512a361e055',
    messagingSenderId: '173268327760',
    projectId: 'corona-d3062',
    authDomain: 'corona-d3062.firebaseapp.com',
    storageBucket: 'corona-d3062.appspot.com',
    measurementId: 'G-KF0DKY3ZF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiImfjC2GgvotNNieeH_Hk6ZA1n0Y7Ts0',
    appId: '1:173268327760:android:2dc5f632bc4fb74f61e055',
    messagingSenderId: '173268327760',
    projectId: 'corona-d3062',
    storageBucket: 'corona-d3062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcEH1dCjP_CkyJV1bdj5ZGHJYKIsbSDuU',
    appId: '1:173268327760:ios:df64e273d383b0e061e055',
    messagingSenderId: '173268327760',
    projectId: 'corona-d3062',
    storageBucket: 'corona-d3062.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcEH1dCjP_CkyJV1bdj5ZGHJYKIsbSDuU',
    appId: '1:173268327760:ios:3a443a47c3f9611861e055',
    messagingSenderId: '173268327760',
    projectId: 'corona-d3062',
    storageBucket: 'corona-d3062.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
