// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7ueQtQ-8tMHFIBSsTRHb4Hfm3SUvcvA',
    appId: '1:519520270059:web:0e4c1509815257609670ae',
    messagingSenderId: '519520270059',
    projectId: 'workshop-9b100',
    authDomain: 'workshop-9b100.firebaseapp.com',
    storageBucket: 'workshop-9b100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfMsBt9iaL_76bpB2_E-6Jf-PGZ2OfHVc',
    appId: '1:519520270059:android:b7dc07cab8b1dec79670ae',
    messagingSenderId: '519520270059',
    projectId: 'workshop-9b100',
    storageBucket: 'workshop-9b100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY5wcCR0G-FEqjqyr-yuiU50hSEbtH-nw',
    appId: '1:519520270059:ios:006819df0685ff099670ae',
    messagingSenderId: '519520270059',
    projectId: 'workshop-9b100',
    storageBucket: 'workshop-9b100.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY5wcCR0G-FEqjqyr-yuiU50hSEbtH-nw',
    appId: '1:519520270059:ios:eedbea4c59eba1cd9670ae',
    messagingSenderId: '519520270059',
    projectId: 'workshop-9b100',
    storageBucket: 'workshop-9b100.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
